#!/bin/bash
set -euo pipefail
umask 077
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
AUDERE_DIR="$( cd "$SELF_DIR/../.." && pwd)"

case "$#" in
  1) ;;
  *) echo 1>&2 "Error: expected one instance tag argument, got $# arguments"; exit 1;;
esac

function get-ssh-user() {
  if [[ "$1" == *@* ]]; then
    echo "${1%@*}"
  else
    echo "ubuntu"
  fi
}

function get-ssh-itag() {
  if [[ "$1" == *@* ]]; then
    echo "${1##*@}"
  else
    echo "$1"
  fi
}

SSH_USER="$(get-ssh-user "$1")"
SSH_ITAG="$(get-ssh-itag "$1")"
SSH_INSTANCE="$($SELF_DIR/aws-instance-unique running "$SSH_ITAG")"
SSH_IP="$(echo "$SSH_INSTANCE" | jq --raw-output '.PublicIpAddress')"

echo "Waiting for sshd to be ready.."
until ssh "-oStrictHostKeyChecking=accept-new" "$SSH_USER@${SSH_IP}" true; do
  sleep 1
done

echo "Syncing audere to '$SSH_USER@$SSH_IP' ('$SSH_ITAG')"
rsync -a --exclude "/learn/" --exclude "/.git/" "$AUDERE_DIR/" "$SSH_USER@$SSH_IP:audere/"
"$SELF_DIR/build-tag-dns" | ssh "$SSH_USER@$SSH_IP" "cat >audere/scripts/tag-dns && chmod +x audere/scripts/tag-dns"
