#!/bin/bash
# Copyright (c) 2019 by Audere
#
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.

# Sets Fever-specific env variables then calls root build-app

set -euo pipefail

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"
PRODUCT=fever
APP_ROOT_DIR="$REPO_ROOT_DIR/FluStudy_us"
source "$REPO_ROOT_DIR/scripts/build-app" "$@"
