#!/bin/bash
# Copyright (c) 2018 by Audere
#
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.

set -euo pipefail

USAGE="Usage: json2csv [FluTrack|FluStudy]" 
TODAY="$(date +%Y%m%d)"

case "$#" in 
  1) TARGET="$1";;
  *) echo 1>&2 "$USAGE"; exit 1;;
esac

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

case "$1" in 
  "FluTrack") APP_DIR="$REPO_ROOT_DIR/learn/ReactNativeTS/FluTrack";;
  "FluStudy") APP_DIR="$REPO_ROOT_DIR/FluStudy";;
  *) echo 1>&2 "$USAGE"; exit 1;;
esac

JSON_DIR="$APP_DIR/src/i18n/locales"

type i18next-json-csv-converter >/dev/null 2>&1 || yarn global add i18next-json-csv-converter 

for jsonfile in "$JSON_DIR"/*.json; do 
  echo "Converting $jsonfile to csv"
  FILENAME=`basename $jsonfile`
  LANGUAGE="${FILENAME:0:2}"
  i18next-json-csv-converter "$JSON_DIR/$LANGUAGE.json" "$JSON_DIR/${LANGUAGE}_${TODAY}.csv"
done

echo "Next, upload the .csv files in $JSON_DIR to Google Sheets and share with translator."
