#!/bin/bash
set -euo pipefail
set -x
umask 077
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

JDK_REV=181
JDK="jdk1.8.0_$JDK_REV"
JDK_TGZ="jdk-8u$JDK_REV-linux-x64.tar.gz"

# --------------------------------------------------------------------------------

function echo2() { echo 1>&2 "$*"; }
function banner() { set +x; echo2 "========== $* =========="; set -x; }

# --------------------------------------------------------------------------------

banner "Creating and loading ~/.commcare-rc"
> "$HOME/.commcare-rc" cat "$SELF_DIR/manage-nvm"
>>"$HOME/.commcare-rc" cat <<-EOF

  JAVA_HOME="\$HOME/.local/$JDK"
  PATH="\$HOME/.local/bin:\$JAVA_HOME/bin:\$PATH"
  . "$HOME/.local/bin/virtualenvwrapper.sh"
  workon commcare-hq
EOF
PROFILE="$( [[ -e "$HOME/.bash_profile" ]] && echo "$HOME/.bash_profile" || echo "$HOME/.profile" )"
if ! grep "commcare-rc" "$PROFILE" >/dev/null; then
  echo >>"$PROFILE" ''
  echo >>"$PROFILE" '. "$HOME/.commcare-rc"'
fi

# --------------------------------------------------------------------------------
banner "Installing JDK"

mkdir -p "$HOME/.local"
pushd "$HOME/.local"
curl http://"$("$SELF_DIR/tag-dns" fileshare)/$JDK_TGZ" -o "$JDK_TGZ"
tar xzf "$JDK_TGZ"
popd

# --------------------------------------------------------------------------------

banner "Cloning commcare-hq"
git clone https://github.com/dimagi/commcare-hq
cd commcare-hq
git submodule update --init --recursive

# --------------------------------------------------------------------------------

cp "localsettings.example.py" "localsettings.py"

# If this fails, fix localsettings.py and regenerate patch with:
#   diff --unified localsettings{.example,}.py >onenode-localsettings.py.patch
# Then check in the .patch file wherever this script is checked in.
patch --unified --input="$SELF_DIR/onenode-localsettings.py.patch" "localsettings.py"

mkdir "$HOME/sharedfiles"

# --------------------------------------------------------------------------------

banner "Setting up Python environment"

pip install --upgrade pip
hash -r
pip install --user virtualenv virtualenvwrapper
hash -r

set +eu
. "$HOME/.local/bin/virtualenvwrapper.sh"
mkvirtualenv --no-site-packages commcare-hq -p python2.7 || exit 1
. "$HOME/.commcare-rc"
set -eu

pip install docker-compose
pip install -r requirements/requirements.txt
pip install -r requirements/dev-requirements.txt
pip install -r requirements/prod-requirements.txt

# --------------------------------------------------------------------------------

banner "Initializing services"

set +x
./scripts/docker up -d postgres couch redis elasticsearch kafka
set -x

while true; do
  httpcode="$(curl --write-out "%{http_code}" --silent --output /dev/null http://127.0.0.1:5984/commcarehq__app)" \
    && (( "$httpcode" < 500 )) \
    && break
  echo2 "Waiting for CouchDB to start..."
  sleep 1
done
./manage.py sync_couch_views
./manage.py create_kafka_topics
env CCHQ_IS_FRESH_INSTALL=1 ./manage.py migrate --noinput
./manage.py compilejsi18n
./manage.py ptop_preindex
./manage.py ptop_es_manage --flip_all_aliases

# --------------------------------------------------------------------------------

banner "Installing nvm, node lts/carbon, and build tools"

set +x
nvm-upd
nvm install lts/carbon
set -x

npm install -g npm
npm install -g bower
bower install
npm install "$(node -p "require('./package.json').dependencies['js-xpath']")"

# --------------------------------------------------------------------------------

banner "Offline LESS compression"

npm install -g less
npm install -g uglify-js@2.6.1
(
  # Generated static files need to be readable to webserver
  umask 022
  ./manage.py collectstatic --noinput
  ./manage.py compilejsi18n
  ./manage.py fix_less_imports_collectstatic
  ./manage.py compress
)

# --------------------------------------------------------------------------------

banner "Installing latest formplayer jar"

curl https://raw.githubusercontent.com/dimagi/formplayer/master/config/application.example.properties -o formplayer.properties
curl https://s3.amazonaws.com/dimagi-formplayer-jars/latest-successful/formplayer.jar -o formplayer.jar

# --------------------------------------------------------------------------------

cat >"$HOME/commcare-start" <<EOF
#!/bin/bash
set -o pipefail
echo \$\$ >\$HOME/commcare-PID
. "\$HOME/.commcare-rc"
./scripts/docker up -d
exec ./manage.py runserver 0.0.0.0:8000
EOF
chmod a+x "$HOME/commcare-start"

cat >"$HOME/commcare-stop" <<EOF
#!/bin/bash
set -euo pipefail
./scripts/docker stop
kill "\$(cat "\$HOME/commcare-PID")"
EOF
chmod a+x "$HOME/commcare-stop"

cat >"$HOME/commcare-ptop-start" <<EOF
#!/bin/bash
set -o pipefail
echo \$\$ >\$HOME/commcare-ptop-PID
. "\$HOME/.commcare-rc"
exec ./manage.py runserver 0.0.0.0:8000
EOF
chmod a+x "$HOME/commcare-ptop-start"

cat >"$HOME/commcare-ptop-stop" <<EOF
#!/bin/bash
set -euo pipefail
kill "\$(cat "\$HOME/commcare-ptop-PID")"
EOF
chmod a+x "$HOME/commcare-ptop-stop"

cat >"$HOME/commcare-celery-start" <<EOF
#!/bin/bash
set -o pipefail
echo \$\$ >\$HOME/commcare-celery-PID
. "\$HOME/.commcare-rc"
exec ./manage.py runserver 0.0.0.0:8000
EOF
chmod a+x "$HOME/commcare-celery-start"

cat >"$HOME/commcare-celery-stop" <<EOF
#!/bin/bash
set -euo pipefail
kill "\$(cat "\$HOME/commcare-celery-PID")"
EOF
chmod a+x "$HOME/commcare-celery-stop"

# --------------------------------------------------------------------------------
