#!/bin/bash
# Copyright (c) 2019 by Audere
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.

set -euo pipefail
umask 077
readonly SELF_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

function echorun() {
  BRIGHT='\033[1m'
  NORMAL='\033[0m'
  echo -e "$ ${BRIGHT}${*}${NORMAL}" 1>&2
  "$@"
}

function package_slack_lambda() {
  curl -L https://github.com/arabold/aws-to-slack/releases/download/1.3.0/release.zip --output release.zip
  local checksum="c95bf872942225d1d3d05d43044c5b9aec84d195da1e24a14153efbfe125cda3"
  if ! shasum -a 256 -c <<< "${checksum} *release.zip"; then
    echo "aws-to-slack checksum failed"
    exit 1
  fi
}

readonly DIR_="$SELF_DIR/../../../local/notifier"
rm -rf "$DIR_"
mkdir -p "$DIR_"
readonly DIR="$(cd "$DIR_" && pwd)"

(
  cd $DIR
  echorun package_slack_lambda
  pwd
  echorun ls -l
)
