#!/bin/bash
# Copyright (c) 2018 by Audere
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.

set -euo pipefail
umask 077
readonly SELF_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

function echorun() {
  BRIGHT='\033[1m'
  NORMAL='\033[0m'
  echo -e "$ ${BRIGHT}${*}${NORMAL}" 1>&2
  "$@"
}

function write_random() {
  set +e
  tr -dc "A-Za-z0-9" </dev/urandom 2>/dev/null | head -c "$1" >"$2"
  set -e
}

function tar_bz2_base64() {
  (
    readonly src="$1"
    readonly dst="$2"
    cd "$(dirname "$src")"
    tar cj "$(basename "$src")" | base64 >"$dst.tar.bz2.base64"
  )
}

readonly FLU_="$SELF_DIR/../../local/flu"
rm -rf "$FLU_"
mkdir -p "$FLU_"
readonly FLU="$(cd "$FLU_" && pwd)"
readonly CREDS="$FLU/creds"
mkdir -p "$FLU/creds"

echorun write_random 16 "$CREDS/db_setup_password"
echorun write_random 1024 "$CREDS/random_seed"

readonly GITHUB="$FLU/github"
mkdir -p "$GITHUB"
echorun ssh-keygen -t rsa -b 4096 -C "test@auderenow.org" -f "$GITHUB/id_rsa" -N ""
echorun tar_bz2_base64 "$GITHUB" "$CREDS/github"
echo "================================================================================"
echo ""
echo "  ACTION REQUIRED:"
echo ""
echo "    Add the public key at '$GITHUB/id_rsa.pub'"
echo "    to the list at 'https://github.com/AudereNow/audere/settings/keys'"
echo ""
if [[ "$MACHTYPE" =~ apple-darwin ]]; then
  echo "    Opening id_rsa.pub in TextEdit and the GitHub page for you..."
  echo ""
  open -e "$GITHUB/id_rsa.pub"
  open "https://github.com/AudereNow/audere/settings/keys"
fi
echo "================================================================================"

(
  cd $FLU
  pwd
  echorun ls -AFlR
)
