# Generated by Django 2.1.1 on 2018-09-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonPush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('timestamp', models.DateTimeField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
