#!/bin/bash
set -euo pipefail
set -x
umask 077
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

> "$HOME/.api-rc" cat "$SELF_DIR/manage-nvm"
>>"$HOME/.api-rc" cat <<-EOF

	PATH="\$HOME/.yarn/bin:\$HOME/.local/bin:\$PATH"
EOF
PROFILE="$( [[ -e "$HOME/.bash_profile" ]] && echo "$HOME/.bash_profile" || echo "$HOME/.profile" )"
if ! grep "api-rc" "$PROFILE" >/dev/null; then
  echo >>"$PROFILE" ''
  echo >>"$PROFILE" '. "$HOME/.api-rc"'
fi
. $HOME/.api-rc

# DB configuration is based on .pgpass, which is assumed to be provided out of band
DBID="db0"

PGPASS="$(grep "^$DBID\." "$HOME/.pgpass")"
function pgpass() { echo "$PGPASS" | cut -d ":" -f "$1"; }

DB_HOSTNAME="$(pgpass 1)"
DB_PORT="$(pgpass 2)"
DB_DATABASE="$(pgpass 3)"
DB_USERNAME="$(pgpass 4)"
DB_PASSWORD="$(pgpass 5)"

echo "DATABASE_URL=postgres://$DB_USERNAME:$DB_PASSWORD@$DB_HOSTNAME:$DB_PORT/$DB_DATABASE" >\
  $HOME/NodeJSWebService/.env

# Install service

yarn global add pm2
(
  cd "$HOME/NodeJSWebService"
  yarn install --frozen-lockfile
  yarn build
  pm2 start process.json --env production
  pm2 save
)
