#!/bin/bash
set -euo pipefail
set -x
umask 077
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# From https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-16-04

> "$HOME/.api-rc" cat "$SELF_DIR/manage-nvm"
>>"$HOME/.api-rc" cat <<-EOF

	PATH="\$HOME/.yarn/bin:\$HOME/.local/bin:\$PATH"
EOF
PROFILE="$( [[ -e "$HOME/.bash_profile" ]] && echo "$HOME/.bash_profile" || echo "$HOME/.profile" )"
if ! grep "api-rc" "$PROFILE" >/dev/null; then
  echo >>"$PROFILE" ''
  echo >>"$PROFILE" '. "$HOME/.api-rc"'
fi
. $HOME/.api-rc

yarn global add pm2
(
  cd "$HOME/NodeJSWebService"
  yarn install --frozen-lockfile
  yarn build
  pm2 start process.json --env production
  pm2 save
)
