#!/bin/bash
set -euo pipefail
set -x
umask 077
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

case "$#" in
  1) ;;
  *) set +x; echo 1>&2 "Error: expected one subdomain argument, got $# arguments"; exit 1;;
esac
SUBDOMAIN=$1

if [[ ! -r "$HOME/.pgpass" ]]; then
  set +x
  echo 1>&2 "Error: cannot access '$HOME/.pgpass' to get database information"
  echo 1>&2 "  Check the AWS console to find the 'fileshare' instance, log in"
  echo 1>&2 "  there via ssh, and copy the contents of '/data/creds/pgpass'."
  exit 1
fi

# Add yarn's debian package repository
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

# Use the node setup script to add the nodesource repository
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

sudo apt update
sudo apt -y full-upgrade
sudo apt -y install postgresql-client-common nginx yarn nodejs

"$SELF_DIR/add-developer-accounts"
sudo adduser --shell /bin/bash --gecos "Audere Api" --disabled-password api
sudo rsync --chown=api:api --chmod="go-rwx" -a "$HOME/.ssh" "$HOME/.pgpass" "$HOME/NodeJSWebService" ~api

(
  cd ~api
  sudo -H --login --user=api bash "$SELF_DIR/api-init"
)

sudo /home/api/.yarn/bin/pm2 startup -u api --hp /home/api --service-name flu-api-pm2

"$SELF_DIR/ubuntu-install-nginx-ssl" "$SUBDOMAIN.auderenow.io" "http://localhost:3000" ~api/NodeJSWebService
