#!/bin/bash
set -euo pipefail
set -x
umask 077
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

sudo apt update && sudo apt -y full-upgrade

"$SELF_DIR/ubuntu-install-docker"

sudo apt -y install \
  git python-pip python-dev libxml2-dev libxslt1-dev zlib1g-dev \
  libncurses5-dev

sudo adduser --shell /bin/bash --gecos "CommCare HQ" --disabled-password commcare
sudo adduser commcare docker
sudo rsync --chown=commcare:commcare --chmod="go-rwx" -a ~/.ssh ~commcare

( cd ~commcare && sudo --login --user=commcare bash "$SELF_DIR/commcare-init" )

sudo reboot
