#!/bin/bash
set -euo pipefail
set -x
umask 077
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# Inspired by:
# https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-16-04

sudo apt update && sudo apt -y full-upgrade

sudo apt -y install python3-pip python3-dev libpq-dev postgresql postgresql-contrib nginx

DB_PASSWORD="$(tr -dc A-Za-z0-9 < /dev/urandom | head -c "${1:-24}")" \
  || true # tr reports failure because its output is truncated

sudo -u postgres psql <<EOF
	CREATE DATABASE fludb;
	CREATE USER fluser WITH PASSWORD '$DB_PASSWORD';
	ALTER ROLE fluser SET client_encoding TO 'utf8';
	ALTER ROLE fluser SET default_transaction_isolation TO 'read committed';
	ALTER ROLE fluser SET timezone TO 'UTC';
	GRANT ALL PRIVILEGES ON DATABASE fludb TO fluser;
EOF

echo "$DB_PASSWORD" >"$HOME/.db-password"

sudo adduser --shell /bin/bash --gecos "Audere Api" --disabled-password api
sudo rsync --chown=api:api --chmod="go-rwx" -a "$HOME/.ssh" "$HOME/.db-password" "$HOME/DjangoWebService" ~api

(
  cd ~api
  sudo -H --login --user=api bash "$SELF_DIR/api-init"
)

(
  umask 022
  sudo rsync --chown=root:root --chmod="go-wx" "$SELF_DIR/api-gunicorn.service" "/etc/systemd/system/api-gunicorn.service"
  sudo rsync --chown=root:root --chmod="go-wx" "$SELF_DIR/api-gunicorn.socket"  "/etc/systemd/system/api-gunicorn.socket"
  sudo rsync --chown=root:root --chmod="go-wx" "$SELF_DIR/api-gunicorn.conf"    "/etc/tmpfiles.d/api-gunicorn.conf"
  sudo systemctl daemon-reload
  sudo systemctl enable --now api-gunicorn.socket
)

"$SELF_DIR/ubuntu-install-nginx-ssl" "api.auderenow.io" "http://unix:/run/gunicorn/AudereWeb.socket" ~api/DjangoWebService/AudereWeb/static
