#!/bin/bash
set -euo pipefail
set -x
umask 077
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

SUBDOMAIN="$1"
PUBLIC_IP="$("$SELF_DIR/client/aws-instance-unique" running "$SUBDOMAIN" | jq --raw-output '.PublicIpAddress')"

# Bash brace expansion can mess up JSON in the heredoc, disable it
set +B

aws route53 change-resource-record-sets --hosted-zone-id Z2JVHTT9LKA76J --change-batch file://<(
  cat <<-EOF
		{
		  "Changes": [{
		    "Action": "UPSERT",
		    "ResourceRecordSet": {
		      "Name": "$SUBDOMAIN.auderenow.io",
		      "Type": "A",
		      "TTL": 300,
		      "ResourceRecords": [{
		        "Value": "$PUBLIC_IP"
		      }]
		    }
		  }]
		}
	EOF
)
echo "DNS record updated for $SUBDOMAIN.auderenow.io"
