#!/usr/bin/env bash
# This will increment FluTrack ios.buildNumber in app.json and then trigger Circle build-ios job 

USAGE="Usage: build-app-ios release-channel commit-hash branch [--no-increment]"
case "$#" in
  3) ;;
  4) if [ "$4" != "--no-increment" ]; then echo 1>&2 $USAGE; exit 1; fi;;
  *) echo 1>&2 $USAGE; exit 1;;
esac

if [[ -z "$CIRCLE_TOKEN" ]]; then
  echo 1>&2 "Error: CIRCLE_TOKEN env variable is not set. Set this before running this script."
  echo 1>&2 "       If you have no API token, get one here: https://circleci.com/account/api"
  exit 1 
fi

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"
CHANNEL=$1
COMMIT=$2
BRANCH=$3

if [ "$#" -ne 4 ]; then source $REPO_ROOT_DIR/scripts/increment-ios-build-number; fi 

set -x
curl --user ${CIRCLE_TOKEN}:\
     -X POST\
     --header "Content-Type: application/json"\
     -d '{"revision": "'$COMMIT'", "build_parameters": {"CIRCLE_JOB": "build_ios", "EXPO_RELEASE_CHANNEL": "'$CHANNEL'"}}' \
https://circleci.com/api/v1.1/project/github/AudereNow/learn/tree/$BRANCH
