#!/bin/bash
# Copyright (c) 2018 by Audere
#
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.

set -euo pipefail

if [ -e "rdt_version_android" ]; then
  RDT_VERSION_ANDROID=$(cat rdt_version_android)
  jq ". + {\"rdtVersionAndroid\": \"$RDT_VERSION_ANDROID\"}" < buildInfo.json > buildInfo.json.new
  mv buildInfo.json.new buildInfo.json
fi
if [ -e "rdt_version_ios" ]; then
  RDT_VERSION_IOS=$(cat rdt_version_ios)
  jq ". + {\"rdtVersionIos\": \"$RDT_VERSION_IOS\"}" < buildInfo.json > buildInfo.json.new
  mv buildInfo.json.new buildInfo.json
fi
