#!/bin/bash
# Copyright (c) 2018 by Audere
#
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.

# First argument is path to product dir
# Second argument is where to write buildInfo.json, if different from product dir (optional)

set -euo pipefail

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"
PRODUCT_DIR="$REPO_ROOT_DIR/$1"
if [[ "$#" -eq 2 ]]; then 
  TARGET_DIR="$REPO_ROOT_DIR/$2"
else 
  TARGET_DIR="$PRODUCT_DIR"
fi 
FILENAME="buildInfo.json"
TODAY="$(date +%Y%m%d)"

PRODUCT_NAME="$(node --eval 'console.log(require("'$PRODUCT_DIR'/package.json").name)')"
PRODUCT_VERSION="$(node --eval 'console.log(require("'$PRODUCT_DIR'/package.json").version)')"

if [ "${CIRCLECI:-}" = true ] && [ -n "$CIRCLE_SHA1" ]; then
  # Ask Circle for the hash; this will be accurate for tagged builds 
  GITHASH="$CIRCLE_SHA1"
else 
  GITHASH="$(git rev-list -n 1 HEAD)"
fi

mkdir -p "$TARGET_DIR"
cat >"$TARGET_DIR/$FILENAME" <<EOT
{
  "name": "$PRODUCT_NAME",
  "version": "$PRODUCT_VERSION",  
  "buildDate": "$TODAY",
  "hash": "$GITHASH"
}
EOT

cd $PRODUCT_DIR
$REPO_ROOT_DIR/scripts/extend-build-info
