#!/bin/bash
REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"
APP_DIR="$REPO_ROOT_DIR/learn/ReactNativeTS/FluTrack"
SERVER_DIR="$REPO_ROOT_DIR/learn/NodeJSWebService/static"
FILENAME="buildInfo.json"
TODAY="$(date +%Y%m%d)"
if [ "$CIRCLECI" = true ] && [ -n "$CIRCLE_SHA1" ]; then
  # Ask Circle for the hash; this will be accurate for tagged builds 
  GITHASH="$CIRCLE_SHA1"
else 
  GITHASH="$(git rev-list -n 1 HEAD)"
fi

cat >"$APP_DIR/$FILENAME" <<EOT
{
  "buildDate": "$TODAY",
  "hash": "$GITHASH"
}
EOT
			  
mkdir -p "$SERVER_DIR"
cat >"$SERVER_DIR/$FILENAME" <<EOT
{
  "buildDate": "$TODAY",
  "hash": "$GITHASH"
}
EOT
