#!/bin/bash
# Copyright (c) 2018 by Audere
#
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.
#
# Downloads cached pods from S3 and unzip into FluStudy/ios/Pods 

set -euo pipefail

HASH="fa4179661dbee1f664d38a650632f04f8b00490f6004678d0a75485338c63b20"
DATE="2019-03-13"
PODS_FILENAME="$DATE.$HASH.Pods.tar.bz2"

PODS_URL="https://s3-us-west-2.amazonaws.com/build-artifacts.auderenow.io/$PODS_FILENAME"
REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

cd "$REPO_ROOT_DIR/FluStudy/ios"
echo "Downloading pods from $PODS_URL"
curl "$PODS_URL" -o "Pods.tar.bz2"
#sha256sum "Pods.tar.bz2" | grep "$HASH"
echo "Expanding tar file"
tar xjf "Pods.tar.bz2"
echo "Removing tar file"
rm "Pods.tar.bz2"
