#!/bin/bash
# Copyright (c) 2018 by Audere
#
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.
#
# Downloads cached pods from S3 and unzip into FluStudy/ios/Pods 

set -euo pipefail

HASH="222fcca5923abf1b91f61e453df64cdb20b0c2e5bbbbf0b99497d96554135dd9"
DATE="2019-03-13"
PODS_FILENAME="$DATE.$HASH.Pods.tar.bz2"

PODS_URL="https://s3-us-west-2.amazonaws.com/build-artifacts.auderenow.io/$PODS_FILENAME"
REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

cd "$REPO_ROOT_DIR/FluStudy/ios"
echo "Downloading pods from $PODS_URL"
curl "$PODS_URL" -o "Pods.tar.bz2"
#sha256sum "Pods.tar.bz2" | grep "$HASH"
echo "Expanding tar file"
tar xjf "Pods.tar.bz2"
echo "Removing tar file"
rm "Pods.tar.bz2"
