#!/bin/bash
# Copyright (c) 2018 by Audere
#
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.

# Called by build-app-ios

set -euo pipefail

if [ -n "$(git status --porcelain)" ]; then
  echo "Error: Cannot increment build number. You have uncommitted changes; please commit first."
  git status
  exit 1
fi

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"
APP_DIR="$REPO_ROOT_DIR/learn/ReactNativeTS/FluTrack"
BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
VERSION_FILE="$APP_DIR/app.json"
IOS_BUILD_NUM="$(node --eval 'console.log(require("'$VERSION_FILE'").expo.ios.buildNumber)')"

((IOS_BUILD_NUM++))

read -p "Will increment ios.buildNumber to $IOS_BUILD_NUM and commit to $BRANCH. Press Enter to continue or Ctrl-C to abort."

sed -i '' -E "s/buildNumber\": \"[0-9]+\"/buildNumber\": \"$IOS_BUILD_NUM\"/" $VERSION_FILE $VERSION_FILE

git add $VERSION_FILE
git commit -m "Build script incrementing ios.buildNumber to $IOS_BUILD_NUM"
git push origin $BRANCH
