#!/bin/bash
#
# Copyright (c) 2018 by Audere
#
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.
set -euo pipefail

readonly remote="$1"
shift

echo "Enabling local sshd (requires sudo)"
sudo systemsetup -setremotelogin on

(
  echo "Connecting to '$remote' and forwarding ~/.aws via sshfs"
  ssh \
    -A \
    -R 22222:localhost:22 \
    -t "$remote" \
    "
      umask 077 &&\
      mkdir -p .local-aws &&\
      sshfs -p 22222 -o idmap=user,allow_other,nonempty,ro $USER@localhost:$HOME/.aws .local-aws &&\
      "${@:-bash}"
      fusermount -u .local-aws
      rmdir .local-aws
    "
) || true

echo "Disabling local sshd (requires sudo)"
sudo systemsetup -f -setremotelogin off
