#!/bin/bash
set -euo pipefail
set -x
umask 077
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

function echo2() { 1>&2 echo "$*"; }

sudo add-apt-repository -y ppa:certbot/certbot
sudo apt update
sudo apt -y install nginx python-certbot-nginx

DOMAIN="$1"
PORT="$2"

sudo certbot -n --agree-tos -m info@auderenow.org --nginx -d $DOMAIN

# certbot makes a bunch of changes to this file
# but we don't care about the default configuration anyways
sudo rm /etc/nginx/sites-enabled/default

{
cat <<-EOF
server {
  listen 80;
  listen [::]:80;
  server_name $DOMAIN;

  location / {
    rewrite ^ https://\$host\$request_uri? permanent;
  }

  location ^~ /.well-known {
    allow all;
    root  /data/letsencrypt/;
  }

}

server {
  server_name $DOMAIN;

  listen [::]:443 ssl ipv6only=on;
  listen 443 ssl;
  ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  location / {
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header Host \$http_host;
    proxy_set_header X-NginX-Proxy true;

    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \"upgrade\";

    proxy_pass http://127.0.0.1:$PORT/;
    proxy_redirect off;
  }
}

EOF
} | sudo tee "/etc/nginx/sites-enabled/$DOMAIN"

# Check the config before restarting
sudo nginx -t
sudo service nginx restart
