#!/bin/bash
set -euo pipefail
set -x
umask 077
SELF_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
AUDERE="$(cd "$SELF_DIR/.." && pwd)"

cd "$AUDERE/FluStudy"
yarn install --frozen-lockfile

cd "$AUDERE/FluStudy/ios"
/usr/local/bin/pod install --repo-update
tar cjf "Pods.tar.bz2" "Pods"
hash="$(sha256sum "Pods.tar.bz2" | awk '{print $1}')"
date="$(date "+%Y-%m-%d")"
archive="$date.$hash.Pods.tar.bz2"
mv "Pods.tar.bz2" "$HOME/Downloads/$archive"
aws s3 cp \
    "$HOME/Downloads/$archive" \
    "s3://build-artifacts.auderenow.io/" \
    --grants "read=uri=http://acs.amazonaws.com/groups/global/AllUsers"

echo "Please update '$AUDERE/scripts/get-cached-pods' to set HASH and DATE:"
echo ""
echo "HASH=$hash"
echo "DATE=$date"
