#!/bin/bash
# Copyright (c) 2019 by Audere
#
# Use of this source code is governed by an MIT-style license that
# can be found in the LICENSE file distributed with this file.

# This script copies everything from the rdt reader repositories
# into our repo. Invoke with an argument to copy changes from
# our repo upstream to the rdt reader repositories

REPO_ROOT=$(git rev-parse --show-toplevel)

RDT_ANDROID_ROOT=${RDT_ANDROID_DIR:-$REPO_ROOT/../rdt-capture}
RDT_IOS_ROOT=${RDT_IOS_DIR:-$REPO_ROOT/../rdt-reader-ios}

cd $RDT_ANDROID_ROOT
git stash
git checkout flu-refactor
git pull
VERSION="$(git remote get-url origin) $(git log -1 --pretty=format:%h)"
cd $REPO_ROOT/FluStudy_au/android/app/src/main/java/edu/washington/cs/ubicomplab/rdt_reader
for f in *
do 
  FROM=$RDT_ANDROID_ROOT/app/src/main/java/edu/washington/cs/ubicomplab/rdt_reader/$f
  TO=$f
  if [ $# -eq 0 ]
  then
    cp $FROM $TO
  else 
    cp $TO $FROM
  fi
done
FROM=$RDT_ANDROID_ROOT/app/src/main/res/drawable-nodpi/
TO=$REPO_ROOT/FluStudy_au/android/app/src/main/res/drawable-nodpi/
if [ $# -eq 0 ]
then
  cp $FROM/* $TO
  echo $VERSION > $REPO_ROOT/FluStudy_au/rdt_version_android
else 
  cp $TO/* $FROM
fi

cd $RDT_IOS_ROOT
git stash
git checkout master
git pull
VERSION="$(git remote get-url origin) $(git log -1 --pretty=format:%h)"
cd $REPO_ROOT/FluStudy_au/ios/fluathome/RDTReader
for f in *.{h,mm}
do 
  FROM=$RDT_IOS_ROOT/Rdt-iOS/Rdt-iOS/$f
  TO=$f
  if [ $# -eq 0 ]
  then
    cp $FROM $TO
  else
    cp $TO $FROM
  fi
done
if [ $# -eq 0 ]
then
  cp $RDT_IOS_ROOT/Rdt-iOS/Rdt-iOS/quickvue*.jpg $REPO_ROOT/FluStudy_au/assets/images/
  echo $VERSION > $REPO_ROOT/FluStudy_au/rdt_version_ios
fi
