# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

default_platform(:android)

platform :android do
  desc "Build signed release apk and deploy to Internal track"
  lane :internal do
    track = "internal"
    gradle(
      task: "clean assemble",
      flavor: "prodKernel",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV["FEVER_SIGNING_STORE_FILE"],
        "android.injected.signing.store.password" => ENV["FEVER_SIGNING_STORE_PWD"],
        "android.injected.signing.key.alias" => ENV["FEVER_SIGNING_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["FEVER_SIGNING_KEY_PWD"],
      }
    )
    upload_to_play_store(
      track: track,
      json_key: "google_play_key.json",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
    slack_announce(
      destination: "Play Store #{track} track"
    )
  end

  lane :slack_announce do |options|
    build = Helper.backticks("cat ../app/version.properties | grep \"VERSION_CODE\" | cut -d'=' -f2").strip
    destination = options[:destination]
    ENV["SLACK_URL"] = ENV["SLACK_WEBHOOK"]
    slack(
      message: "flu@home Australia build #{build} has been uploaded to #{destination} :rocket:",
      default_payloads: [:git_branch, :last_git_commit_hash],
      payload: {
        "Built by" => ENV["CIRCLE_USERNAME"],
        "Description" => ENV["BUILD_DESCRIPTION"],
        "Release Type" => ENV["EXPO_RELEASE_CHANNEL"]
      }
    )
  end

end
