#!/bin/bash
set -euo pipefail
umask 077

while true; do
  echo "$(date): Opening connection"
  ssh bastion \
    -N \
    -o ExitOnForwardFailure=yes \
    -o ServerAliveInterval=60 \
    -R localhost:12894:localhost:22
  echo "$(date): Disconnected, waiting before retry"
  sleep 5
done
