# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :beta do
  sync_code_signing(type: "appstore")
  build_app(scheme: "fluathome Production",
            include_bitcode: true)
  upload_to_testflight
end

####### Certificates #######

desc "Installs the certificates and profiles locally"
lane :certificates do |options|
  if options[:use_temporary_keychain]
    create_temporary_keychain
  end

  readonly = (options[:refresh_certificates] ? false : true)
  force_for_new_devices = !readonly

  match(
    git_branch: "master",
    app_identifier: "org.auderenow.fluathome.dev",
    team_id: "G8UCCFY788",
    type: "development",
    readonly: readonly,
    force_for_new_devices: force_for_new_devices
  )

  match(
    git_branch: "master",
    app_identifier: "org.auderenow.fluathome.staging",
    team_id: "G8UCCFY788",
    type: "appstore",
    readonly: readonly
  )

  match(
    git_branch: "master",
    app_identifier: "org.auderenow.fluathome",
    team_id: "G8UCCFY788",
    type: "appstore",
    readonly: readonly
  )

  if options[:use_temporary_keychain]
    sh "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{ENV["KEYCHAIN_NAME"]} #{ENV["KEYCHAIN_PASSWORD"]}"
  end
end

private_lane :create_temporary_keychain do
  keychain_name = "temporary_keychain"
  ENV["KEYCHAIN_NAME"] = keychain_name
  ENV["KEYCHAIN_PASSWORD"] = keychain_name
  ENV["MATCH_KEYCHAIN_NAME"] = keychain_name 
  ENV["MATCH_KEYCHAIN_PASSWORD"] = keychain_name

  create_keychain(
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true
  )
end
